### ISSUE TITLE
Add JSON information for all the 3 federal territories (Kuala Lumpur, Labuan and Putrajaya)

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/malaysia-api#14]
Currently, it can be seen that, there is an entry at 

https://github.com/JianLoong/malaysia-api/blob/main/state/v1/selangor.json which actually leads to this [end point](https://jianliew.me/malaysia-api/state/v1/selangor.json).

So, a Labuan.json should be created which contains information with regards to the state of Labuan. 

Information with regards to the state can be obtained [here](https://en.wikipedia.org/wiki/Labuan).

This applies to Kuala Lumpur and Putrajaya as well.

The JSON files should contain the information should have similar output with the Selangor.json. Please also remember that the JSON file should be valid. (Please use a JSON validator to ensure that it is a valid JSON file).

**Comment by amimaro** [comment]
Hi! May I take a look at this one?

**Comment by underscoremissa** [comment]
Hello, can you assign this role to me?
Thankyou.

**Comment by JianLoong** [comment]
This has been solved with #17. Closing this issue.
