### ISSUE TITLE
Adding of unemployment rate by state 

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/malaysia-api#35]
There is a fair amount of data available from the Malaysia Open Data [website](https://www.data.gov.my/)

It would be great if the unemployment data for each state could be added to the API.  The data itself can be obtained from [here](https://www.data.gov.my/data/ms_MY/dataset/labour-force-statistics-malaysia-1092). However, there might be some data missing or the information there might be incomplete.

It is not needed to add all the years to the API but just for the year 2020.

**Comment by jeslyw** [comment]
would like to work on this @JianLoong - could you let me know where exactly in each state's file the data needs to be added?

**Comment by JianLoong** [comment]
Hello! @jeslyw 

Take the file [Johor](https://github.com/JianLoong/malaysia-api/blob/main/state/v1/johor.json) for example, you can add the unemployment information as follows.

![image](https://user-images.githubusercontent.com/933858/193807197-c3824e15-abeb-4f6a-96f8-60f6355290af.png)

If there is no information available for the unemployment rate, you can just use the value "NA"

I shall assign this to you for now. Do tell me if you need further clarification.

**Comment by jeslyw** [comment]
Done, see [PR](https://github.com/JianLoong/malaysia-api/pull/39) :)

**Comment by JianLoong** [comment]
Closing this issue as it was handled in #39
