### ISSUE TITLE
Adding of number active and inactive vehicles on road.

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/malaysia-api#36]
There is a fair amount of data available from the Malaysia Open Data [website](https://www.data.gov.my/)

It would be great if the number of vehicles on road can be added to the API.  The data itself can be obtained from [here](https://www.data.gov.my/data/ms_MY/dataset/bilangan-kenderaan-di-atas-jalan-raya-mengikut-negeri-number-of-vehicles-on-the-road-by-state). However, there might be some data missing or the information there might be incomplete. If so, these should be marked as "NA". Please note that there are two numbers, the number of active vehicles and the number of inactive vehicles.

**Comment by Mannuel25** [comment]
Hello @JianLoong , I'd love to take this up. Kindly assign it to me. Here's what I'd do; for each state I'll add two new fields called `total_active_vehicles`, `total_inactive_vehicles` then enter their values.

**Comment by JianLoong** [comment]
Sure, I have assigned this to you. @Mannuel25

**Comment by Mannuel25** [comment]
Thank you!
