### ISSUE TITLE
Updating and adding of various flag and crest URL.

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/malaysia-api#44]
Currently, the flag and crest URLs of the various states point to the Wikipedia website entry. (Where the user can choose the download the SVG or PNG file). 

This can be improved by adding the path to the image itself instead.

For example in the file `state/v1/johor.json` the 

**"flag_url"** information is currenty

"https://en.wikipedia.org/wiki/Johor#/media/File:Flag_of_Johor.svg"
 
when it should be instead 

"https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Johor.svg"

This is the same as several other entries.

Besides that, several states are also missing this information including, Kedah, Kelantan and a few others.

**Comment by AraanBranco** [comment]
I can working on this?

**Comment by JianLoong** [comment]
Sure. Assigned it to you. 👍
